services:
  - type: web
    name: pictionary-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: REDIS_HOST
        value: pictionary-redis
    instances: 1
    ports:
      - name: http
        port: 8000
  - type: private-service
    name: pictionary-redis
    env: docker
    dockerfilePath: ./redis.Dockerfile
    plan: free
    docker:
      instances: 1
      ports:
        - port: 6379
