name: CI/CD

on:
  push:
    branches: [feat/create_join_room]
    paths:
      - "main.py"
      - "tests/"
      - "requirements.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependenciaes
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Testing the Python Code!"
          pytest -v tests
