name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Print working directory
        run: |
          echo "pwd is:"
          pwd
          echo "ls is:"
          ls

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Install dependenciaes
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -c "import os; print(os.listdir())"
          echo "Testing the Python Code!"
          pytest -v tests
